name = "omefans-backend-api"
main = "src/worker.ts"
compatibility_date = "2024-07-18"

[[d1_databases]]
binding = "DB" # This is the name your worker will use to access the database.
database_name = "omefans-gallery-db"
database_id = "<PASTE_YOUR_NEW_DATABASE_ID_HERE>"
