name = "omefans-backend-api"
main = "src/worker.ts"
compatibility_date = "2024-07-18"

[[d1_databases]]
binding = "DB" # This is the name your worker will use to access the database.
database_name = "omefans-gallery-db"
<<<<<<< HEAD
database_id = "096b1ec8-c718-4dee-84df-7aa08f824003"
=======
database_id = "096b1ec8-c718-4dee-84df-7aa08f824003"
>>>>>>> b6d90df51a4bc7fbb6dece3910056818d9298a3b
